<?php

use Drupal\Core\Form\FormStateInterface;

function upload_test_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  
  if ($form_id == 'upload_test_form') {
    
    $form['#submit'][] = 'upload_test_upload_test_form_submit';
  }
}

function upload_test_upload_test_form_submit(array &$form, FormStateInterface $form_state) {
  // Get the form values.
  $form_values = $form_state->getValues();

  // Do something with the form data.  For example, log it.
  \Drupal::logger('upload_test')->notice('Form data: @data', [
    'data' => print_r($form_values, TRUE),
  ]);

  
  $csv_fid = $form_state->getValue('csv_file')[0]; // Get the file ID.
  $image_fids = $form_state->getValue('image_files');
  
    
}